[package]
name = "task2"
version = "0.2.0"
edition = "2024"

[dependencies]
bit_writer_reader = {path = "bit_writer_reader"}
bool_vec = { path = "bit_writer_reader/bool_vec" }
inquire = "0.9.1"
inquire-derive = "0.9.1"

[features]
write_foo = []
#bool_vec_macro = []